### ISSUE TITLE
onProgress has no state at the end of a download

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-sdk#5] opened 2015-01-26 14:42 UTC
The onProgress callback from `resin.models.os.download` doesn't return `state` when it reaches the end of the download.

Using the example `resin.models.os.download` code:

```
parameters =
		network: 'ethernet'
		appId: 91

resin.models.os.download parameters, '/opt/os.zip', (error) ->
		throw error if error?
	, (state) ->
		console.log "Total: #{state.total}"
		console.log "Received: #{state.received}"
```
gives the error:

```
Total: 107564591
Received: 106094176
Total: 107564591
Received: 106946144

/Users/hobochild/Documents/resin/autoTestPi/app.coffee:41
          console.log("Total: " + state.total);
                                       ^
TypeError: Cannot read property 'total' of undefined
  at Request.<anonymous> (/Users/hobochild/Documents/resin/autoTestPi/app.coffee:27:38)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/hobochild/Documents/resin/autoTestPi/node_modules/resin-sdk/node_modules/request/request.js:1266:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:938:16
  at process._tickCallback (node.js:419:13)
```

**Comment by jviotti** [comment] 2015-01-26 14:52
An easy fix is to add `return if not state?` at the beginning of the `onProgress()` callback, however we should prevent `onProgress()` to get called with no state in the last call.

**Comment by jviotti** [comment] 2015-02-04 15:27
The issue is fixed now. `return if no state?` is not necessary anymore.

**Closed by jviotti** 2015-02-04 15:27 UTC
Labels: bug
